#
# Vivado (TM) v2015.4 (64-bit)
#
# write_project_tcl.tcl: Tcl script for re-creating project 'XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter'
#
# Generated by Vivado on Thu Dec 17 19:08:46 +0100 2015
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (write_project_tcl.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_mon_sipo.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_mon_piso.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_mon_fifo.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/voter.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_mon.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_cfg.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_example.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/design_1.bd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_single_core.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/constrs_1/imports/new/xdc1.xdc"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/constrs_2/imports/new/xdc1.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/ip/sem_core/sem_core.xci"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/ip/clk_wiz/clk_wiz.xci"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/new/topsystem.vhd"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_AXItmrmvoter_0_1/design_1_AXItmrmvoter_0_1.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_4/design_1_lmb_bram_4.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_5/design_1_lmb_bram_5.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1/design_1_microblaze_0_1.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_axi_periph_0/design_1_microblaze_1_axi_periph_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_clk_wiz_1_0/design_1_microblaze_1_clk_wiz_1_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_0/design_1_microblaze_2_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_axi_periph_0/design_1_microblaze_2_axi_periph_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_clk_wiz_1_0/design_1_microblaze_2_clk_wiz_1_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_3_axi_periph_0/design_1_microblaze_3_axi_periph_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_3_clk_wiz_1_0/design_1_microblaze_3_clk_wiz_1_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_0/design_1_microblaze_4_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_axi_periph_0/design_1_microblaze_4_axi_periph_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_clk_wiz_1_0/design_1_microblaze_4_clk_wiz_1_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_5_axi_periph_0/design_1_microblaze_5_axi_periph_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_5_clk_wiz_1_0/design_1_microblaze_5_clk_wiz_1_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_1/design_1_memconformitymodule_0_1.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_3/design_1_memconformitymodule_0_3.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_4/design_1_memconformitymodule_0_4.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrit_0_0/design_1_tmrit_0_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_0/design_1_tmrmvoter_3_0.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_1/design_1_tmrmvoter_3_1.upgrade_log"
#    "D:/SEUDProject/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_2/design_1_tmrmvoter_3_2.upgrade_log"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "write_project_tcl.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter ./XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7a200tsbg484-1" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../ip_repo/chtimer"] [file normalize "$origin_dir/../ip_repo/tmrmvoter"] [file normalize "$origin_dir/../ip_repo/AXItmrmvoter_1.0"] [file normalize "$origin_dir/../ip_repo/tmrit"] [file normalize "$origin_dir/../ip_repo"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/ip/sem_core/sem_core.xci"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/ip/clk_wiz/clk_wiz.xci"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/new/topsystem.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_AXItmrmvoter_0_1/design_1_AXItmrmvoter_0_1.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_4/design_1_lmb_bram_4.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_5/design_1_lmb_bram_5.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1/design_1_microblaze_0_1.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_axi_periph_0/design_1_microblaze_1_axi_periph_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_clk_wiz_1_0/design_1_microblaze_1_clk_wiz_1_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_0/design_1_microblaze_2_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_axi_periph_0/design_1_microblaze_2_axi_periph_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_clk_wiz_1_0/design_1_microblaze_2_clk_wiz_1_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_3_axi_periph_0/design_1_microblaze_3_axi_periph_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_3_clk_wiz_1_0/design_1_microblaze_3_clk_wiz_1_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_0/design_1_microblaze_4_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_axi_periph_0/design_1_microblaze_4_axi_periph_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_clk_wiz_1_0/design_1_microblaze_4_clk_wiz_1_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_5_axi_periph_0/design_1_microblaze_5_axi_periph_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_5_clk_wiz_1_0/design_1_microblaze_5_clk_wiz_1_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_1/design_1_memconformitymodule_0_1.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_3/design_1_memconformitymodule_0_3.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_4/design_1_memconformitymodule_0_4.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrit_0_0/design_1_tmrit_0_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_0/design_1_tmrmvoter_3_0.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_1/design_1_tmrmvoter_3_1.upgrade_log"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_2/design_1_tmrmvoter_3_2.upgrade_log"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_mon_sipo.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_mon_piso.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_mon_fifo.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/voter.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_mon.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_cfg.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_core_sem_example.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/design_1.bd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/imports/vhdl_srcs/sem_single_core.vhd"]"\
 "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd"]"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/ip/sem_core/sem_core.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/ip/clk_wiz/clk_wiz.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/new/topsystem.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_AXItmrmvoter_0_1/design_1_AXItmrmvoter_0_1.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_1/design_1_lmb_bram_1.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_4/design_1_lmb_bram_4.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_5/design_1_lmb_bram_5.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_1/design_1_microblaze_0_1.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_0/design_1_microblaze_1_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_axi_periph_0/design_1_microblaze_1_axi_periph_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_1_clk_wiz_1_0/design_1_microblaze_1_clk_wiz_1_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_0/design_1_microblaze_2_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_axi_periph_0/design_1_microblaze_2_axi_periph_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_2_clk_wiz_1_0/design_1_microblaze_2_clk_wiz_1_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_3_axi_periph_0/design_1_microblaze_3_axi_periph_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_3_clk_wiz_1_0/design_1_microblaze_3_clk_wiz_1_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_0/design_1_microblaze_4_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_axi_periph_0/design_1_microblaze_4_axi_periph_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_4_clk_wiz_1_0/design_1_microblaze_4_clk_wiz_1_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_5_axi_periph_0/design_1_microblaze_5_axi_periph_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_microblaze_5_clk_wiz_1_0/design_1_microblaze_5_clk_wiz_1_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_1/design_1_memconformitymodule_0_1.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_3/design_1_memconformitymodule_0_3.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_memconformitymodule_0_4/design_1_memconformitymodule_0_4.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrit_0_0/design_1_tmrit_0_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_0/design_1_tmrmvoter_3_0.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_1/design_1_tmrmvoter_3_1.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/sources_1/bd/design_1/ip/design_1_tmrmvoter_3_2/design_1_tmrmvoter_3_2.upgrade_log"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj


# Set 'sources_1' fileset file properties for local files
set file "vhdl_srcs/sem_core_sem_mon_sipo.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "vhdl_srcs/sem_core_sem_mon_piso.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "vhdl_srcs/sem_core_sem_mon_fifo.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "vhdl_srcs/voter.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "vhdl_srcs/sem_core_sem_mon.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "vhdl_srcs/sem_core_sem_cfg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "vhdl_srcs/sem_core_sem_example.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "design_1/design_1.bd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}
if { ![get_property "is_locked" $file_obj] } {
  set_property "is_locked" "1" $file_obj
}

set file "vhdl_srcs/sem_single_core.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "hdl/design_1_wrapper.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "topsystem" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/constrs_1/imports/new/xdc1.xdc"]"
set file_imported [import_files -fileset constrs_1 $file]
set file "new/xdc1.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "is_enabled" "0" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'constrs_2' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_2] ""]} {
  create_fileset -constrset constrs_2
}

# Set 'constrs_2' fileset object
set obj [get_filesets constrs_2]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter.srcs/constrs_2/imports/new/xdc1.xdc"]"
set file_imported [import_files -fileset constrs_2 $file]
set file "new/xdc1.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_2] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_2' fileset properties
set obj [get_filesets constrs_2]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "topsystem" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7a200tsbg484-1 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_2
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "constrset" "constrs_2" $obj
set_property "part" "xc7a200tsbg484-1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7a200tsbg484-1 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_2 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "constrset" "constrs_2" $obj
set_property "part" "xc7a200tsbg484-1" $obj
set_property "steps.write_bitstream.args.raw_bitfile" "1" $obj
set_property "steps.write_bitstream.args.mask_file" "1" $obj
set_property "steps.write_bitstream.args.bin_file" "1" $obj
set_property "steps.write_bitstream.args.readback_file" "1" $obj
set_property "steps.write_bitstream.args.logic_location_file" "1" $obj
set_property "steps.write_bitstream.args.verbose" "1" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:XA200T_TMRMBwGPO_TMRMBwUART_ThroughVoter"
